### ISSUE TITLE
(do) function not working in TypeScript 2.3.4

### ISSUE THREAD

**Issue by DedSec49** [gund/ng-http-interceptor#158]
res.do line gives an error : 
[ts] Property 'do' does not exist on type 'Observable<Response>'.

`httpInterceptor.response().addInterceptor((res, method) => {
      return res.do(r => console.log(method, r));
    });`

Please help.
Thanks.

**Comment by gund** [comment]
That is probably related to how RxJs works.
You have to make sure you imported `do` operator:
```ts
import 'rxjs/add/operator/do';
```

**Comment by DedSec49** [comment]
Thanks, It worked..
